# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Copy project files
COPY pyproject.toml README.md /app/
COPY src /app/src

# Install dependencies and the package
RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir .

# Default command uses the installed entrypoint; API key passed at runtime
CMD ["atla-mcp-server"]
