name: Publishing

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build distribution
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Build
        run: uv build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment: release
    needs: [build]
    permissions:
      id-token: write

    steps:
      - name: Retrieve release distribution
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Publish package distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
