name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  python-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Setup Python environment
        run: |
          uv venv
          . .venv/bin/activate
          uv pip install -e ".[dev]"

      - name: Run ruff checks
        run: |
          . .venv/bin/activate
          ruff check .
          ruff format --check .

      - name: Run mypy checks
        run: |
          . .venv/bin/activate
          dmypy run -- .
